
(in-package :eliza-test)

(pat-match-abbrev '?x* '(?* ?x))
(pat-match-abbrev '?y* '(?* ?y))

(defparameter *eliza-rules-pt*
  '(((?x* Olá ?y*)
     (Olá eu sou a Eliza. Qual o seu nome?))
    ((?x* Eu me chamo ?y*)
     (Prazer em conhece-lo ?y Por favor fale sobre o seu problema.))
    ((?x* Eu quero ?y*)
     (O que significaria se você conseguisse ?y ?)
     (Por que você quer ?y ?) 
     (Você acredita que conseguirá ?y ?))
    ((?x* eu estou ?y*)
     (Por que você está ?y ?)
     (Você quer estar ?y ?))
    ((?x* Não ?y*)
     (Por que não?)
     (Você está sendo um pouco negativo))
    ((?x* desculpe ?y*)
     (Por favor não se Desculpe))
    ((?x* triste ?y*)
     (Você não deveria se sentir triste por algo assim)
     (E ruim saber que você não está feliz))
    ((?x* minha mae ?y*)
     (Conte-me mais sobre sua familia)
     (Quem mais e da sua familia?))
    ((?x* meu pai ?y*)
     (Ele influencia na sua vida?)
     (O que você pensa sobre seu pai?))
    ((?x* sonho ?y*)
     (Com o que mais você sonha?)
     (Que pessoas apareceram em seus sonhos?))
    ((?x* eu quero ?y*)
     (Por que você quer ?y ?)
     (O que você fara quando tiver ?y ?))
    ((?x* sonhei com ?y*)
     (Você gosta de ?y)
     (Por que você acha que sonhou com ?y ?))
    ((?x* gosto ?y*)
     (Por que você gosta tanto de ?y ?)
     (Sera que você gosta tanto de ?y quanto você pensa?))
    ((?x* sim ?y*)
     (Eu compreendo)
     (Fico feliz com essa sua positividade))
    ((?x* eu sinto ?y*)
     (Com que frequencia você sente ?y ?))
    ((?x* porque ?y*)
     (Esse e o real motivo?)
     (Tem certeza que e isso?))
    ((?x* não gosto ?y*)
     (Porque sera que você não gosta?)
     (O que faz você não gostar?))
    ((?x* Eu sou ?y*)
     (Serio que você é ?y ?)
     (Conte-me mais sobre ser ?y ))
    ((?x* Por que ?y*)
     (Esse é o verdadeiro motivo?)
     (Quais outros motivos poderiam existir?)
     (Esse motivo pode explicar alguma outra coisa?))
    ((?x* Tchau ?y*)
     (Adeus. exit))
    ((?x*)               
     (Hmmm. Interessante. Fale mais sobre isto)
     (Mesmo? Não tenho certeza se entendi o seu motivo)
     (O que você pensa sobre isto?)
     (Por favor me fale mais sobre isto. Parece bem interessante)
     (Não me sinto confortável em falar mais sobre isto) 
     (Tem certeza que você está falando?)
     (Assim fico sem graça. Vamos mudar de assunto))))


(defun switch-viewpoint-pt (words)
  (sublis '((eu . você) (você . eu))
          words))
